# Generated by Django 4.2.4 on 2023-08-21 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerProfile',
            new_name='UserProfile',
        ),
    ]
